adding order of errors test

diff --git a/treater-error-tampered-file/detect-problematic-files b/treater-error-tampered-file/detect-problematic-files
--- a/treater-error-tampered-file/detect-problematic-files
+++ b/treater-error-tampered-file/detect-problematic-files
@@ -16,3 +16,19 @@ then
     echo 'did not print out error message for error'
     exit 22
 fi
+
+# there should only be one error file
+seen=no
+for q in $MVE_CONFIGS/$CONFIG/errors/*
+do
+    if [ $seen = yes ]
+    then
+        echo 'more than one error file'
+        exit 23
+    fi
+
+    export ERROR_FILE="$q"
+    pytest test_errors_correct_order.py
+
+    seen=yes
+done
