setup env sanity checking

diff --git a/setup-env b/setup-env
--- a/setup-env
+++ b/setup-env
@@ -1,5 +1,13 @@
 #!/bin/dash
 
+if [ ! -d ../../mve/src ]
+then
+    echo "$(basename $0) failed because ../../mve/src doesn't exist"
+    echo "the mve project folder must exist in the parent of mve-tests"
+    exit 15
+fi
+cp -r ../../mve/src .
+
 export CONFIG=testing
 export MVE_CONFIGS='../configs'
 
@@ -33,8 +41,6 @@ cat << EOF > config.json
 }
 EOF
 cd ../..
-
-cp -r ../../mve/src .
 
 cd src
 python3 generator.py $CONFIG > /dev/null
