fully modular tests

diff --git a/error-integration/run b/error-integration/run
--- a/error-integration/run
+++ b/error-integration/run
@@ -1,8 +1,18 @@
 #!/bin/dash
 
-# set to a non-empty string value to turn on
-VIEW=''
-
 ../setup-env
 
-test-middle
+run_all() {
+    file="$1"
+    if ! "$1"
+    then
+        echo ''
+        echo "failed $0"
+        exit 1
+    fi
+
+    echo ''
+    echo "passed tests: $0"
+}
+
+run_all test-middle
